### ISSUE TITLE
Passing links object causes TypeError

### ISSUE THREAD

**Issue by wijnandhonselaar** [marissen/marissen-ecurring-api-php#1]
Acquired your API client today and I'm having some issues in an otherwise very easy to use package.

When retrieving data from eCurring, like customers  I'm running into an error.

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Marissen\\eCurring\\Endpoint\\CustomerEndpoint::getResourceCollectionObject() must be an instance of Marissen\\eCurring\\Endpoint\\object, instance of stdClass given, called in /sites/site_1/vendor/marissen/ecurring-api-php/src/Endpoint/AbstractEndpoint.php on line 88 and defined in /sites/site_1/vendor/marissen/ecurring-api-php/src/Endpoint/CustomerEndpoint.php:30\nStack trace:\n#0 /sites/site_1/vendor/marissen/ecurring-api-php/src/Endpoint/AbstractEndpoint.php(88): Marissen\\eCurring\\Endpoint\\CustomerEndpoint->getResourceCollectionObject(5, Object(stdClass))\n#1 /sites/site_1/vendor/marissen/ecurring-api-php/src/Endpoint/CustomerEndpoint.php(69): Marissen\\eCurring\\Endpoint\\AbstractEndpoint->rest_list(1, 10, Array)\n#2 /sites/site_1/services/eCurring/customerService.php(14): Marissen\\eCurring\\Endpoint\\CustomerEndpoint->page()\n#3  /sites/site_1/vendor/marissen/ecurring-api-php/src/Endpoint/CustomerEndpoint.php on line 30

Simply casting the original $links value to an object doesn't seem to fix the  issue. I can't seem to figure out what's causing the issue. Removing the type declaration for **ALL** of the object typed parameters solves the issue for now, but I'm curious to see what the problem is..

PHP 7.2
MacOS Mojave 10.14.6

Best regards

**Comment by tdgroot** [comment]
Thank you for using the library!

Are you sure you are running on PHP 7.2? The `object` typehint was added since 7.2, this error shows it does not know the `object` typehint and assumes type `Marissen\eCurring\Endpoint\object`.

**Comment by wijnandhonselaar** [comment]
Good morning, thanks for the reply!

Yes, I've unlinked my PHP 7.1 and installed PHP 7.2 a while ago. 

> $ php --version: PHP 7.2.21 (cli) (built: Aug  6 2019 22:38:21) ( NTS )

I'm using strongly typed parameters throughout my application. Just  the `object` type declaration is causing me any issues.

I've taken a look again and there is no such class in my `Endpoint` folder.

**Comment by tdgroot** [comment]
Great, and you are running the code from web or from cli? 

> I'm using strongly typed parameters throughout my application

Strong typed parameters has been around since PHP 7.0, just specific `object` typehint has been added to PHP 7.2.

**Comment by tdgroot** [comment]
@wijnandhonselaar I published a new version of the package (0.2.0) which does a PHP version check. Please let me know if you get the same error on the new version.

**Comment by wijnandhonselaar** [comment]
Perfect, I'll try it in a few minutes! I'll let you know as soon as I have some results

**Comment by tdgroot** [comment]
Hi @wijnandhonselaar,

Did you get any further with version 0.2.0?

**Comment by tdgroot** [comment]
Closing this due to inactivity. 

If the problem reoccurs, feel free to open the issue.
